# Generated by Django 4.1.3 on 2022-11-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uuid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='部门名称')),
            ],
            options={
                'db_table': 'frontend_departments',
            },
        ),
        migrations.CreateModel(
            name='PivotRbacRoleAndAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uuid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='uuid')),
                ('rbac_role_uuid', models.CharField(max_length=36, verbose_name='所属角色uuid')),
                ('account_uuid', models.CharField(max_length=36, verbose_name='所属用户uuid')),
            ],
            options={
                'db_table': 'frontend_pivot_rbac_role_and_accounts',
            },
        ),
        migrations.CreateModel(
            name='RbacRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uuid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
            ],
            options={
                'db_table': 'frontend_rbac_roles',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uuid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='昵称')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', related_query_name='accounts', to='frontend.department', to_field='uuid', verbose_name='所属部门')),
            ],
            options={
                'db_table': 'frontend_accounts',
            },
        ),
    ]
