# Generated by Django 4.1.3 on 2022-11-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
        migrations.AddField(
            model_name='account',
            name='department_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', related_query_name='accounts', to='frontend.department', to_field='uuid', verbose_name='所属部门'),
        ),
    ]
